var skiData = [{
  "name":"Baker Mountain",
  "nearestTown":"Waterville",
  "state":"Maine",
  "lat":45.084722,
  "long":-69.905556,
  "baseElevation":540,
  "verticalFeet":227,
  "runs":5,
  "website":"http://www.newenglandskihistory.com/Maine/bakermtn.php"
  },
  {
  "name":"Big Rock",
  "nearestTown":"Presque Isle",
  "state":"Maine",
  "lat":46.522222,
  "long": -67.827778,
  "baseElevation":670,
  "verticalFeet":920,
  "runs":27,
  "website":"www.bigrockmaine.com"
},
  {
  "name":"Big Squaw Mountain Resort",
  "nearestTown":"Greenville",
  "state":"Maine",
  "lat":45.504167,
  "long":-69.705556,
  "baseElevation":1300,
  "verticalFeet":1750,
  "runs":33,
  "website":"http://www.nelsap.org/me/squaw.html",
  },
  {
  "name":"Black Mountain of Maine",
  "nearestTown":"Lewiston",
  "state":"Maine",
  "lat":44.58,
  "long":-70.6175,
  "baseElevation":1000,
  "verticalFeet":1380,
  "runs":35,
  "website":"www.skiblackmountain.org"
  },
  {
  "name":"Camden Snow Bowl",
  "nearestTown":"Camden",
  "state":"Maine",
  "lat":44.217216,
  "long":-69.134667,
  "baseElevation":235,
  "verticalFeet":845,
  "runs":17,
  "website":"http://www.camdensnowbowl.com/"
  },
  {
  "name":"Eaton Mountain",
  "nearestTown":"Waterville",
  "state":"Maine",
  "lat":44.768056,
  "long":-69.619444,
  "baseElevation":220,
  "verticalFeet":620,
  "runs":18,
  "website":"http://www.eatonmountain.com/home.html",
  },
  {
  "name":"Lost Valley Ski Area",
  "nearestTown":"Auburn",
  "state":"Maine",
  "lat":44.136,
  "long":-70.281,
  "baseElevation":240,
  "verticalFeet":240,
  "runs":18,
  "website":"www.lostvalleyski.com"
  },
  {
  "name":"Mount Abram",
  "nearestTown":"Bethel",
  "state":"Maine",
  "lat":44.379167,
  "long":-70.706944,
  "baseElevation":940,
  "verticalFeet":1050,
  "runs":44,
  "website":"www.mtabram.com"
  },
  {
  "name":"Powderhouse Hill",
  "nearestTown":"Portland",
  "state":"Maine",
  "lat":43.236944,
  "long":-70.802222,
  "baseElevation":null,
  "verticalFeet":null,
  "runs":null,
  "website":""
  },
  {
  "name":"Saddleback Maine",
  "nearestTown":"Farmington",
  "state":"Maine",
  "lat":44.936667,
  "long":-70.503056,
  "baseElevation":2120,
  "verticalFeet":2000,
  "runs":66,
  "website":"http://www.majellagroup.com/saddlebackmaine/"
  },
  {
  "name":"Shawnee Peak Ski Area",
  "nearestTown":"Bridgton",
  "state":"Maine",
  "lat":44.058333,
  "long":-70.815278,
  "baseElevation":null,
  "verticalFeet":1300,
  "runs":44,
  "website":"www.shawneepeak.com"
  },
  {
  "name":"Sugarloaf",
  "nearestTown":"Farmington",
  "state":"Maine",
  "lat":45.031389,
  "long":-70.313056,
  "baseElevation":1417,
  "verticalFeet":2820,
  "runs":160,
  "website":"www.sugarloaf.com"
  },
  {
  "name":"Sunday River Ski Resort",
  "nearestTown":"Auburn",
  "state":"Maine",
  "lat":44.469444,
  "long":-70.861111,
  "baseElevation":800,
  "verticalFeet":1340,
  "runs":135,
  "website":"www.sundayriver.com"
  },
  {
  "name":"Titcomb Mountain",
  "nearestTown":"Augusta",
  "state":"Maine",
  "lat":44.65,
  "long":-70.170833,
  "baseElevation":400,
  "verticalFeet":350,
  "runs":16,
  "website":"www.titcombmountain.com"
  },

  {
  "name":"Berkshire East Ski Resort",
  "nearestTown":"Greenfield",
  "state":"Massachusetts",
  "lat":42.620833,
  "long":-72.876944,
  "baseElevation":null,
  "verticalFeet":null,
  "runs":45,
  "website":"www.berkshireeast.com"
  },
  {
  "name":"Blandford Ski Area",
  "nearestTown":"Blandford",
  "state":"Massachusetts",
  "lat":42.188851,
  "long":-72.900768,
  "baseElevation":1025,
  "verticalFeet":465,
  "runs":23,
  "website":"https://skiblandford.com/"
  },
  {
  "name":"Blue Hills Ski Area",
  "nearestTown":"Boston",
  "state":"Massachusetts",
  "lat":42.215278,
  "long":-71.119167,
  "baseElevation":null,
  "verticalFeet":309,
  "runs":8,
  "website":"www.ski-bluehills.com"
  },
  {
  "name":"Ski Butternut",
  "nearestTown":"Great Barrington",
  "state":"Massachusetts",
  "lat":42.183788,
  "long":-73.320232,
  "baseElevation":825,
  "verticalFeet":939,
  "runs":22,
  "website":"http://skibutternut.com/"
  },
  {
  "name":"Jiminy Peak",
  "nearestTown":"Pittsfield",
  "state":"Massachusetts",
  "lat":42.555516,
  "long":-73.292058,
  "baseElevation":1245,
  "verticalFeet":1150,
  "runs":45,
  "website":"http://www.jiminypeak.com/"
  },
  {
  "name":"Nashoba Valley Ski Area",
  "nearestTown":"Boston",
  "state":"Massachusetts",
  "lat":42.541975,
  "long":-71.444103,
  "baseElevation":194,
  "verticalFeet":240,
  "runs":17,
  "website":"https://www.skinashoba.com/"
  },
  {
  "name":"Ski Bradford",
  "nearestTown":"Haverhill",
  "state":"Massachusetts",
  "lat":42.745261,
  "long":-71.055708,
  "baseElevation":49,
  "verticalFeet":213,
  "runs":23,
  "website":"http://skibradford.com/"
  },
  {
  "name":"Ski Ward",
  "nearestTown":"Worchester",
  "state":"Massachusetts",
  "lat":42.305556,
  "long":-71.675,
  "baseElevation":null,
  "verticalFeet":220,
  "runs":9,
  "website":"https://www.skiward.com/"
  },
  {
  "name":"Wachusett Mountain",
  "nearestTown":"Worchester",
  "state":"Massachusetts",
  "lat":42.499444,
  "long":-71.886389,
  "baseElevation":1000,
  "verticalFeet":1006,
  "runs":26,
  "website":"http://www.wachusett.com"
  },

  {
  "name":"Arrowhead Recreation Area",
  "nearestTown":"Claremont",
  "state":"New Hampshire",
  "lat":43.362778,
  "long":-72.333333,
  "baseElevation":null,
  "verticalFeet":120,
  "runs":9,
  "website":"http://www.arrowheadnh.com/"
  },
  {
  "name":"Attitash Mountain Resort",
  "nearestTown":"North Conway",
  "state":"New Hampshire",
  "lat":44.082222,
  "long":-71.229722,
  "baseElevation":600,
  "verticalFeet":1750,
  "runs":68,
  "website":"www.attitash.com"
  },
  {
  "name":"Black Mountain Ski Area",
  "nearestTown":"Berlin",
  "state":"New Hampshire",
  "lat":44.168333,
  "long":-71.164444,
  "baseElevation":null,
  "verticalFeet":1100,
  "runs":40,
  "website":"https://www.blackmt.com/"
  },
  {
  "name":"Bretton Woods Mountain Resort",
  "nearestTown":"Berlin",
  "state":"New Hampshire",
  "lat":44.259722,
  "long":-71.462222,
  "baseElevation":1600,
  "verticalFeet":1500,
  "runs":102,
  "website":"http://brettonwoods.com/"
  },
  {
  "name":"Cannon Mountain Ski Area",
  "nearestTown":"Franconia",
  "state":"New Hampshire",
  "lat":44.157778,
  "long":-71.698889,
  "baseElevation":1850,
  "verticalFeet":2330,
  "runs":73,
  "website":"www.cannonmt.com"
  },
  {
  "name":"Cranmore Mountain Resort",
  "nearestTown":"North Conway",
  "state":"New Hampshire",
  "lat":44.056389,
  "long":-71.11,
  "baseElevation":null,
  "verticalFeet":1200,
  "runs":54,
  "website":"http://www.cranmore.com/"
  },
  {
  "name":"Crotched Mountain",
  "nearestTown":"Francestown",
  "state":"New Hampshire",
  "lat":42.998294,
  "long":-71.873712,
  "baseElevation":1163,
  "verticalFeet":900,
  "runs":25,
  "website":"https://geonames.usgs.gov/apex/f?p=gnispq:3:0::NO::P3_FID:866414",
  },
  {
  "name":"Dartmouth Skiway",
  "nearestTown":"Lebanon",
  "state":"New Hampshire",
  "lat":43.786667,
  "long":-72.433889,
  "baseElevation":975,
  "verticalFeet":968,
  "runs":30,
  "website":"http://skiway.dartmouth.edu/"
  },
  {
  "name":"Granite Gorge Ski Area",
  "nearestTown":"Keene",
  "state":"New Hampshire",
  "lat":42.970833,
  "long":-72.212222,
  "baseElevation":null,
  "verticalFeet":390,
  "runs":19,
  "website":"http://www.granitegorge.com/"
  },
  {
  "name":"Gunstock Mountain Resort",
  "nearestTown":"Laconia",
  "state":"New Hampshire",
  "lat":43.541389,
  "long":-71.3675,
  "baseElevation":867,
  "verticalFeet":1400,
  "runs":55,
  "website":"https://www.gunstock.com/"
  },
  {
  "name":"King Pine",
  "nearestTown":"Madison",
  "state":"New Hampshire",
  "lat":43.871389,
  "long":-71.089444,
  "baseElevation":null,
  "verticalFeet":350,
  "runs":17,
  "website":"https://www.kingpine.com/"
  },
  {
  "name":"Loon Mountain",
  "nearestTown":"Lincoln",
  "state":"New Hampshire",
  "lat":44.036111,
  "long":-71.621667,
  "baseElevation":950,
  "verticalFeet":2100,
  "runs":61,
  "website":"http://www.loonmtn.com/"
  },
  {
  "name":"McIntyre Ski Area",
  "nearestTown":"Manchester",
  "state":"New Hampshire",
  "lat":43.005,
  "long":-71.44,
  "baseElevation":null,
  "verticalFeet":180,
  "runs":9,
  "website":"http://www.mcintyreskiarea.com/"
  },
  {
  "name":"Mount Sunapee Resort",
  "nearestTown":"Claremont",
  "state":"New Hampshire",
  "lat":43.330556,
  "long":-72.08,
  "baseElevation":1230,
  "verticalFeet":1513,
  "runs":66,
  "website":"http://www.mountsunapee.com/"
  },
  {
  "name":"Pats Peak",
  "nearestTown":"Henniker",
  "state":"New Hampshire",
  "lat":43.163333,
  "long":-71.795833,
  "baseElevation":690,
  "verticalFeet":770,
  "runs":28,
  "website":"https://www.patspeak.com/"
  },
  {
  "name":"Ragged Mountain Resort",
  "nearestTown":"Franklin",
  "state":"New Hampshire",
  "lat":43.484444,
  "long":-71.842222,
  "baseElevation":null,
  "verticalFeet":1250,
  "runs":57,
  "website":"http://www.raggedmountainresort.com/"
  },
  {
  "name":"Tenney Mountain Ski Resort",
  "nearestTown":"Plymouth",
  "state":"New Hampshire",
  "lat":43.737778,
  "long":-71.783611,
  "baseElevation":749,
  "verticalFeet":1400,
  "runs":45,
  "website":"https://www.skitenney.com/"
  },
  {
  "name":"The Balsams Grand Resort Hotel",
  "nearestTown":"Dixville Notch",
  "state":"New Hampshire",
  "lat":44.870556,
  "long":-71.307778,
  "baseElevation":2200,
  "verticalFeet":null,
  "runs":16,
  "website":"https://thebalsamsresort.com/"
  },
  {
  "name":"Waterville Valley Resort",
  "nearestTown":"Plymouth",
  "state":"New Hampshire",
  "lat":43.965278,
  "long":-71.527778,
  "baseElevation":1820,
  "verticalFeet":2020,
  "runs":50,
  "website":"http://www.waterville.com/"
  },
  {
  "name":"Whaleback",
  "nearestTown":"Enfield",
  "state":"New Hampshire",
  "lat":43.601389,
  "long":-72.181389,
  "baseElevation":1100,
  "verticalFeet":700,
  "runs":30,
  "website":"https://www.whaleback.com/"
  },
  {
  "name":"Wildcat Mountain Ski Area",
  "nearestTown":"Jackson",
  "state":"New Hampshire",
  "lat":44.263056,
  "long":-71.238333,
  "baseElevation":1950,
  "verticalFeet":2112,
  "runs":49,
  "website":"https://www.skiwildcat.com/"
  },

  {
  "name":"Yawgoo Valley",
  "nearestTown":"Providence",
  "state":"Rhode Island",
  "lat":41.516944,
  "long":-71.529444,
  "baseElevation":70,
  "verticalFeet":240,
  "runs":14,
  "website":"http://www.yawgoo.com/"
  },

  {
  "name":"Ascutney Mountain Resort",
  "nearestTown":"Windsor",
  "state":"Vermont",
  "lat":43.463333,
  "long":-72.466111,
  "baseElevation":720,
  "verticalFeet":1800,
  "runs":57,
  "website":"www.ascutney.com"
  },
  {
  "name":"Bolton Valley",
  "nearestTown":"Burlington",
  "state":"Vermont",
  "lat":44.415833,
  "long":-72.869722,
  "baseElevation":1446,
  "verticalFeet":1625,
  "runs":71,
  "website":"http://www.boltonvalley.com/"
  },
  {
  "name":"Bromley Mountain",
  "nearestTown":"Manchester",
  "state":"Vermont",
  "lat":43.227778,
  "long":-72.938611,
  "baseElevation":1956,
  "verticalFeet":1334,
  "runs":47,
  "website":"https://www.bromley.com/"
  },
  {
  "name":"Burke Mountain",
  "nearestTown":"Lyndonville",
  "state":"Vermont",
  "lat":44.570833,
  "long":-71.893167,
  "baseElevation":1256,
  "verticalFeet":2011,
  "runs":55,
  "website":"http://skiburke.com/"
  },
  {
  "name":"Jay Peak Resort",
  "nearestTown":"Jay",
  "state":"Vermont",
  "lat":44.929444,
  "long":-72.532222,
  "baseElevation":1843,
  "verticalFeet":2153,
  "runs":76,
  "website":"https://jaypeakresort.com/"
  },
  {
  "name":"Killington Ski Resort",
  "nearestTown":"Rutland",
  "state":"Vermont",
  "lat":43.626,
  "long":-72.798,
  "baseElevation":1165,
  "verticalFeet":3050,
  "runs":155,
  "website":"http://www.killington.com/site/index.html",
  },
  {
  "name":"Mad River Glen",
  "nearestTown":"Fayson",
  "state":"Vermont",
  "lat":44.200833,
  "long":-72.924444,
  "baseElevation":1600,
  "verticalFeet":2000,
  "runs":45,
  "website":"https://www.madriverglen.com/"
  },
  {
  "name":"Magic Mountain Ski Area",
  "nearestTown":"Brattleboro",
  "state":"Vermont",
  "lat":43.192778,
  "long":-72.76,
  "baseElevation":1350,
  "verticalFeet":1500,
  "runs":50,
  "website":"https://www.magicmtn.com/"
  },
  {
  "name":"Middlebury College Snow Bowl",
  "nearestTown":"Hancock",
  "state":"Vermont",
  "lat":43.94,
  "long":-72.96,
  "baseElevation":2720,
  "verticalFeet":1000,
  "runs":17,
  "website":"http://www.middleburysnowbowl.com/"
  },
  {
  "name":"Mount Snow",
  "nearestTown":"Dover",
  "state":"Vermont",
  "lat":37.944167,
  "long":-67.923611,
  "baseElevation":1900,
  "verticalFeet":1500,
  "runs":87,
  "website":"https://www.mountsnow.com/"
  },
  {
  "name":"Okemo Mountain",
  "nearestTown":"Londonderry",
  "state":"Vermont",
  "lat":43.401389,
  "long":-72.716667,
  "baseElevation":1134,
  "verticalFeet":2200,
  "runs":121,
  "website":"https://www.okemo.com/"
  },
  {
  "name":"Pico Mountain",
  "nearestTown":"Rutland",
  "state":"Vermont",
  "lat":43.661667,
  "long":-72.8425,
  "baseElevation":2000,
  "verticalFeet":1967,
  "runs":57,
  "website":"http://www.picomountain.com/site/index.html",
  },
  {
  "name":"Smugglers' Notch Resort",
  "nearestTown":"Burlingon",
  "state":"Vermont",
  "lat":44.572778,
  "long":-72.776111,
  "baseElevation":314,
  "verticalFeet":796,
  "runs":78,
  "website":"http://www.smuggs.com/"
  },
  {
  "name":"Stowe Mountain Resort",
  "nearestTown":"Burlington",
  "state":"Vermont",
  "lat":44.531944,
  "long":-72.7875,
  "baseElevation":1559,
  "verticalFeet":2360,
  "runs":116,
  "website":"https://www.stowe.com/"
  },
  {
  "name":"Stratton Mountain Resort",
  "nearestTown":"Manchester",
  "state":"Vermont",
  "lat":43.114167,
  "long":-72.906667,
  "baseElevation":1872,
  "verticalFeet":2003,
  "runs":97,
  "website":"https://www.stratton.com/"
  },
  {
  "name":"Sugarbush Resort",
  "nearestTown":"Burlington",
  "state":"Vermont",
  "lat":44.135098,
  "long":-72.885962,
  "baseElevation":1483,
  "verticalFeet":2820,
  "runs":111,
  "website":"http://www.sugarbush.com/"
  },
  {
  "name":"Suicide Six",
  "nearestTown":"Pomfret",
  "state":"Vermont",
  "lat":43.663889,
  "long":-72.544444,
  "baseElevation":550,
  "verticalFeet":650,
  "runs":23,
  "website":"https://www.woodstockinn.com/ski-area",
  },

  {
  "name":"Mohawk Mountain Ski Area",
  "nearestTown":"Cornwall",
  "state":"Connecticut",
  "lat":41.83675,
  "long":-73.31342,
  "baseElevation":null,
  "verticalFeet":650,
  "runs":25,
  "website":"http://www.mohawkmtn.com/"
  },
  {
  "name":"Mount Southington",
  "nearestTown":"Waterbury",
  "state":"Connecticut",
  "lat":41.58235,
  "long":-72.92587,
  "baseElevation":100,
  "verticalFeet":425,
  "runs":14,
  "website":"http://mountsouthington.com/"
  },
  {
  "name":"Powder Ridge Ski Area",
  "nearestTown":"Middlefield",
  "state":"Connecticut",
  "lat":41.502006,
  "long":-72.737172,
  "baseElevation":383,
  "verticalFeet":550,
  "runs":19,
  "website":"https://powderridgepark.com/"
  },
  {
  "name":"Ski Sundown",
  "nearestTown":"Hartford",
  "state":"Connecticut",
  "lat":41.88407,
  "long":-72.94523,
  "baseElevation":null,
  "verticalFeet":625,
  "runs":16,
  "website":"http://www.skisundown.com/"
  },

  {
  "name":"Wisp Ski Resort",
  "nearestTown":"McHenry",
  "state":"Maryland",
  "lat":39.558056,
  "long":-79.363056,
  "baseElevation":2415,
  "verticalFeet":700,
  "runs":34,
  "website":"http://www.wispresort.com/"
  },

  {
  "name":"Mountain Creek",
  "nearestTown":"New York City",
  "state":"New Jersey",
  "lat":41.181,
  "long":-74.513,
  "baseElevation":137,
  "verticalFeet":317,
  "runs":46,
  "website":"https://www.mountaincreek.com/"
  },

  {
  "name":"Belleayre Ski Center",
  "nearestTown":"Kingston",
  "state":"New york",
  "lat":42.142214,
  "long":-74.510778,
  "baseElevation":2024,
  "verticalFeet":1404,
  "runs":52,
  "website":"http://www.belleayre.com/"
  },
  {
  "name":"Bristol Mountain Ski Resort",
  "nearestTown":"Canandaigua",
  "state":"New York",
  "lat":42.745,
  "long":-77.404444,
  "baseElevation":1000,
  "verticalFeet":1150,
  "runs":35,
  "website":"http://www.bristolmountain.com/"
  },
  {
  "name":"Catamount Ski Area",
  "nearestTown":"Great Barrington",
  "state":"New York",
  "lat":42.171457,
  "long":-73.477764,
  "baseElevation":1000,
  "verticalFeet":1000,
  "runs":36,
  "website":"http://www.catamountski.com/"
  },
  {
  "name":"Gore Mountain",
  "nearestTown":"Glen Falls",
  "state":"New York",
  "lat":43.672222,
  "long":-74.006944,
  "baseElevation":998,
  "verticalFeet":2537,
  "runs":109,
  "website":"http://www.goremountain.com/"
  },
  {
  "name":"Greek Peak Mountain Resort",
  "nearestTown":"Virgil",
  "state":"New York",
  "lat":42.5086,
  "long":-76.146049,
  "baseElevation":1148,
  "verticalFeet":952,
  "runs":55,
  "website":"http://greekpeak.net/"
  },
  {
  "name":"Holiday Valley",
  "nearestTown":"Buffalo",
  "state":"New York",
  "lat":42.2625,
  "long":-78.668056,
  "baseElevation":1500,
  "verticalFeet":750,
  "runs":58,
  "website":"https://www.holidayvalley.com/"
  },
  {
  "name":"Hunter Mountain",
  "nearestTown":"Kingston",
  "state":"New York",
  "lat":42.200278,
  "long":-74.230278,
  "baseElevation":1600,
  "verticalFeet":1600,
  "runs":58,
  "website":"https://www.huntermtn.com/"
  },
  {
  "name":"McCauley Mountain",
  "nearestTown":"Webb",
  "state":"New York",
  "lat":43.696111,
  "long":-74.961389,
  "baseElevation":null,
  "verticalFeet":633,
  "runs":21,
  "website":"http://www.mccauleyny.com/mountain.html",
  },
  {
  "name":"Peek'n Peak",
  "nearestTown":"Erie",
  "state":"New York",
  "lat":42.0625,
  "long":-79.736667,
  "baseElevation":1400,
  "verticalFeet":400,
  "runs":27,
  "website":"https://www.pknpk.com/"
  },
  {
  "name":"Plattekill Mountain",
  "nearestTown":"Roxbury",
  "state":"New York",
  "lat":42.290251,
  "long":-74.653678,
  "baseElevation":2400,
  "verticalFeet":1100,
  "runs":38,
  "website":"http://plattekill.com/"
  },
  {
  "name":"Thunder Ridge Ski Area",
  "nearestTown":"Patterson",
  "state":"New York",
  "lat":41.507222,
  "long":-73.581111,
  "baseElevation":670,
  "verticalFeet":600,
  "runs":21,
  "website":"http://www.thunderridgeski.com/"
  },
  {
  "name":"Titus Mountain",
  "nearestTown":"Malone",
  "state":"New York",
  "lat":44.763333,
  "long":-74.235278,
  "baseElevation":825,
  "verticalFeet":1200,
  "runs":50,
  "website":"https://www.titusmountain.com/"
  },
  {
  "name":"West Mountain",
  "nearestTown":"Queensbury",
  "state":"New York",
  "lat":43.285556,
  "long":-73.728333,
  "baseElevation":460,
  "verticalFeet":1010,
  "runs":25,
  "website":"https://www.westmtn.net/"
  },
  {
  "name":"Whiteface Mountain",
  "nearestTown":"Lake Placid",
  "state":"New York",
  "lat":44.365833,
  "long":-73.902778,
  "baseElevation":1220,
  "verticalFeet":3430,
  "runs":87,
  "website":"http://www.whiteface.com/"
  },
  {
  "name":"Windham Mountain",
  "nearestTown":"Windham",
  "state":"New York",
  "lat":42.291667,
  "long":-74.259444,
  "baseElevation":1500,
  "verticalFeet":1600,
  "runs":54,
  "website":"http://www.windhammountain.com/"
  },

  {
  "name":"Bear Creek Ski and Recreation Area",
  "nearestTown":"Allentown",
  "state":"Pennsylvania",
  "lat":40.476111,
  "long":-75.625833,
  "baseElevation":590,
  "verticalFeet":510,
  "runs":21,
  "website":"https://www.bcmountainresort.com/"
  },
  {
  "name":"Blue Mountain Ski Area",
  "nearestTown":"Palmerton",
  "state":"Pennsylvania",
  "lat":40.822222,
  "long":-75.513333,
  "baseElevation":458,
  "verticalFeet":1082,
  "runs":39,
  "website":"https://www.skibluemt.com/"
  },
  {
  "name":"Camelback Mountain Resort",
  "nearestTown":"Scranton",
  "state":"Pennsylvania",
  "lat":41.051389,
  "long":-75.355278,
  "baseElevation":1333,
  "verticalFeet":800,
  "runs":35,
  "website":"http://www.skicamelback.com"
  },
  {
  "name":"Elk Mountain Ski Area",
  "nearestTown":"Scranton",
  "state":"Pennsylvania",
  "lat":41.721,
  "long":-75.559,
  "baseElevation":1742,
  "verticalFeet":925,
  "runs":27,
  "website":"https://www.elkskier.com/"
  },
  {
  "name":"Hidden Valley Resort",
  "nearestTown":"Hidden Valley",
  "state":"Pennsylvania",
  "lat":40.058042,
  "long":-79.258277,
  "baseElevation":2405,
  "verticalFeet":470,
  "runs":26,
  "website":"http://www.hiddenvalleyresort.com/"
  },
  {
  "name":"Laurel Mountain Ski Resort",
  "nearestTown":"Ligonier",
  "state":"Pennsylvania",
  "lat":40.163578,
  "long":-79.165300,
  "baseElevation":2000,
  "verticalFeet":800,
  "runs":20,
  "website":"http://www.laurelmountainski.com/"
  },
  {
  "name":"Liberty Mountain Resort",
  "nearestTown":"Gettysburg",
  "state":"Pennsylvania",
  "lat":39.7635,
  "long":-77.375,
  "baseElevation":570,
  "verticalFeet":620,
  "runs":22,
  "website":"http://www.libertymountainresort.com"
  },
  {
  "name":"Mount Pleasant of Edinboro",
  "nearestTown":"Edinboro",
  "state":"Pennsylvania",
  "lat":41.851111,
  "long":-80.070278,
  "baseElevation":801,
  "verticalFeet":350,
  "runs":9,
  "website":"http://www.skimountpleasant.com/"
  },
  {
  "name":"Seven Springs Mountain Resort",
  "nearestTown":"Champion",
  "state":"Pennsylvania",
  "lat":40.023056,
  "long":-79.292778,
  "baseElevation":2240,
  "verticalFeet":750,
  "runs":40,
  "website":"http://www.7springs.com/"
  },
  {
  "name":"Shawnee Mountain Ski Area",
  "nearestTown":"East Stroudsburg",
  "state":"Pennsylvania",
  "lat":41.040833,
  "long":-75.083333,
  "baseElevation":551,
  "verticalFeet":700,
  "runs":23,
  "website":"http://www.shawneemt.com"
  },
  {
  "name":"Ski Big Bear",
  "nearestTown":"Lackawaxen",
  "state":"Pennsylvania",
  "lat":41.523333,
  "long":-75.025,
  "baseElevation":null,
  "verticalFeet":650,
  "runs":18,
  "website":"http://ski-bigbear.com/"
  },
  {
  "name":"Roundtop Mountain Resort",
  "nearestTown":"Lewisberry",
  "state":"Pennsylvania",
  "lat":40.108,
  "long":-76.926,
  "baseElevation":755,
  "verticalFeet":600,
  "runs":20,
  "website":"http://www.skiroundtop.com"
  },
  {
  "name":"Montage Mountain Ski Resort",
  "nearestTown":"Scranton",
  "state":"Pennsylvania",
  "lat":41.3533,
  "long":-75.6592,
  "baseElevation":960,
  "verticalFeet":1000,
  "runs":26,
  "website":"https://www.montagemountainresorts.com/"
  },
  {
  "name":"Tussey Mountain Ski Area",
  "nearestTown":"State College",
  "state":"Pennsylvania",
  "lat":40.7682,
  "long":-77.752,
  "baseElevation":1319,
  "verticalFeet":500,
  "runs":7,
  "website":"http://www.tusseymountain.com/"
  },
  {
  "name":"Whitetail Ski Resort",
  "nearestTown":"Clear Spring",
  "state":"Pennsylvania",
  "lat":39.741667,
  "long":-77.932778,
  "baseElevation":865,
  "verticalFeet":935,
  "runs":25,
  "website":"http://www.skiwhitetail.com"
  },

  {
  "name":"Appalachian Ski Mountain",
  "nearestTown":"Boone",
  "state":"North Carolina",
  "lat":36.174,
  "long":-81.662,
  "baseElevation":3635,
  "verticalFeet":365,
  "runs":11,
  "website":"https://www.appskimtn.com/"
  },
  {
  "name":"Cataloochee Ski Area",
  "nearestTown":"Maggie Valley",
  "state":"North Carolina",
  "lat":35.563,
  "long":-83.09,
  "baseElevation":4660,
  "verticalFeet":740,
  "runs":18,
  "website":"http://cataloochee.com/"
  },
  {
  "name":"Wolf Ridge Ski Resort",
  "nearestTown":"Mars Hill",
  "state":"North Carolina",
  "lat":35.955,
  "long":-82.509,
  "baseElevation":3900,
  "verticalFeet":700,
  "runs":23,
  "website":"http://www.skiwolfridgenc.com/"
  },

  {
  "name":"Ober Gatlinburg",
  "nearestTown":"Gatlinburg",
  "state":"Tennessee",
  "lat":35.703056,
  "long":-83.557778,
  "baseElevation":2700,
  "verticalFeet":600,
  "runs":10,
  "website":"https://obergatlinburg.com/"
  },

  {
  "name":"Bryce Resort",
  "nearestTown":"Mount Jackson",
  "state":"Virginia",
  "lat":38.8175,
  "long":-78.765833,
  "baseElevation":1250,
  "verticalFeet":500,
  "runs":8,
  "website":"http://bryceresort.com/Home.aspx",
  },
  {
  "name":"The Omni Homestead Resort",
  "nearestTown":"Hot Springs",
  "state":"Virginia",
  "lat":37.995472,
  "long":-79.829644,
  "baseElevation":2500,
  "verticalFeet":700,
  "runs":10,
  "website":"https://www.omnihotels.com/hotels/homestead-virginia",
  },
  {
  "name":"Wintergreen Resort",
  "nearestTown":"Nellysford",
  "state":"Virginia",
  "lat":37.93,
  "long":-78.941667,
  "baseElevation":2512,
  "verticalFeet":1003,
  "runs":26,
  "website":"http://www.wintergreenresort.com/"
  },

  {
  "name":"Snowshoe Mountain",
  "nearestTown":"Marlinton",
  "state":"West Virginia",
  "lat":38.408889,
  "long":-79.994722,
  "baseElevation":3348,
  "verticalFeet":1500,
  "runs":60,
  "website":"https://www.snowshoemtn.com/"
  },
  {
  "name":"Winterplace Ski Resort",
  "nearestTown":"Beckley",
  "state":"West Virginia",
  "lat":37.59,
  "long":-81.115,
  "baseElevation":2997,
  "verticalFeet":603,
  "runs":28,
  "website":"https://www.winterplace.com/"
  },

  {
  "name":"Chestnut Mountain",
  "nearestTown":"Dubuque",
  "state":"Illinois",
  "lat":42.319049,
  "long":-90.393686,
  "baseElevation":600,
  "verticalFeet":420,
  "runs":19,
  "website":"https://www.chestnutmtn.com/"
  },

  {
  "name":"Paoli Peaks",
  "nearestTown":"Paoli",
  "state":"Indiana",
  "lat":38.557778,
  "long":-86.510278,
  "baseElevation":900,
  "verticalFeet":300,
  "runs":17,
  "website":"https://www.paolipeaks.com/"
  },
  {
  "name":"Perfect North Slopes",
  "nearestTown":"Lawrenceburg",
  "state":"Indiana",
  "lat":39.149208,
  "long":-84.886581,
  "baseElevation":400,
  "verticalFeet":400,
  "runs":25,
  "website":"https://www.perfectnorth.com//"
  },

  {
  "name":"Big Powderhorn Mountain",
  "nearestTown":"Bessemer",
  "state":"Michigan",
  "lat":46.504167,
  "long":-90.096111,
  "baseElevation":1240,
  "verticalFeet":400,
  "runs":33,
  "website":"http://www.bigpowderhorn.net/"
  },
  {
  "name":"Blackjack Ski Resort",
  "nearestTown":"Bessemer",
  "state":"Michigan",
  "lat":46.5021,
  "long":-90.0046,
  "baseElevation":1200,
  "verticalFeet":420,
  "runs":22,
  "website":"http://www.skiblackjack.com/"
  },
  {
  "name":"Boyne Highlands",
  "nearestTown":"Harbor Springs",
  "state":"Michigan",
  "lat":45.470833,
  "long":-84.934722,
  "baseElevation":773,
  "verticalFeet":552,
  "runs":55,
  "website":"https://www.boynehighlands.com/"
  },
  {
  "name":"Boyne Mountain Resort",
  "nearestTown":"Boyne City",
  "state":"Michigan",
  "lat":45.163889,
  "long":-84.932778,
  "baseElevation":620,
  "verticalFeet":500,
  "runs":60,
  "website":"https://www.boynemountain.com/"
  },
  {
  "name":"Caberfae Peaks Ski & Golf Resort",
  "nearestTown":"Cadillac",
  "state":"Michigan",
  "lat":44.249722,
  "long":-85.725,
  "baseElevation":1060,
  "verticalFeet":485,
  "runs":34,
  "website":"http://caberfaepeaks.com"
  },
  {
  "name":"Crystal Mountain (Michigan)",
  "nearestTown":"Thompsonville",
  "state":"Michigan",
  "lat":44.52,
  "long":-85.992222,
  "baseElevation":757,
  "verticalFeet":375,
  "runs":58,
  "website":"http://www.crystalmountain.com/"
  },
  {
  "name":"Indianhead Mountain",
  "nearestTown":"Wakefield",
  "state":"Michigan",
  "lat":46.5,
  "long":-89.970833,
  "baseElevation":1240,
  "verticalFeet":520,
  "runs":28,
  "website":"http://www.bigsnow.com/"
  },
  {
  "name":"Marquette Mountain",
  "nearestTown":"Marquette",
  "state":"Michigan",
  "lat":46.508,
  "long":-87.42,
  "baseElevation":800,
  "verticalFeet":457,
  "runs":25,
  "website":"http://www.marquettemountain.com/"
  },
  {
  "name":"Mount Bohemia",
  "nearestTown":"Grant Township",
  "state":"Michigan",
  "lat":47.391667,
  "long":-88.013611,
  "baseElevation":null,
  "verticalFeet":900,
  "runs":95,
  "website":"http://www.mtbohemia.com/"
  },
  {
  "name":"Mount Brighton",
  "nearestTown":"Brighton",
  "state":"Michigan",
  "lat":42.538056,
  "long":-83.806944,
  "baseElevation":1100,
  "verticalFeet":230,
  "runs":25,
  "website":"https://www.mtbrighton.com/"
  },
  {
  "name":"Nub's Nob",
  "nearestTown":"Harbor Springs",
  "state":"Michigan",
  "lat":45.468333,
  "long":-84.903611,
  "baseElevation":911,
  "verticalFeet":427,
  "runs":53,
  "website":"http://nubsnob.com"
  },

  {
  "name":"Afton Alps",
  "nearestTown":"Afton",
  "state":"Minnesota",
  "lat":44.855556,
  "long":-92.789167,
  "baseElevation":350,
  "verticalFeet":350,
  "runs":50,
  "website":"https://www.aftonalps.com/"
  },
  {
  "name":"Buck Hill",
  "nearestTown":"Minneapolis",
  "state":"Minnesota",
  "lat":44.724,
  "long":-93.283,
  "baseElevation":949,
  "verticalFeet":262,
  "runs":16,
  "website":"http://www.buckhill.com/"
  },
  {
  "name":"Lutsen Mountains",
  "nearestTown":"Lutsen",
  "state":"Minnesota",
  "lat":47.664,
  "long":-90.714,
  "baseElevation":863,
  "verticalFeet":825,
  "runs":95,
  "website":"https://www.lutsen.com/winter/"
  },
  {
  "name":"Mount Kato",
  "nearestTown":"Mankato",
  "state":"Minnesota",
  "lat":44.131389,
  "long":-94.036389,
  "baseElevation":600,
  "verticalFeet":240,
  "runs":19,
  "website":"https://www.mountkato.com/"
  },
  {
  "name":"Spirit Mountain",
  "nearestTown":"Duluth",
  "state":"Minnesota",
  "lat":46.719444,
  "long":-92.218056,
  "baseElevation":620,
  "verticalFeet":678,
  "runs":22,
  "website":"https://www.spiritmt.com/"
  },
  {
  "name":"Welch Village",
  "nearestTown":"Red Wing",
  "state":"Minnesota",
  "lat":44.560556,
  "long":-92.727222,
  "baseElevation":700,
  "verticalFeet":360,
  "runs":60,
  "website":"http://www.welchvillage.com/"
  },
  {
  "name":"Wild Mountain",
  "nearestTown":"Taylor Falls",
  "state":"Minnesota",
  "lat":45.488889,
  "long":-92.705556,
  "baseElevation":null,
  "verticalFeet":300,
  "runs":26,
  "website":"https://www.wildmountain.com/"
  },

  {
  "name":"Hidden Valley Ski Area",
  "nearestTown":"Wildwood",
  "state":"Missouri",
  "lat":38.535578,
  "long":-90.65287,
  "baseElevation":null,
  "verticalFeet":312,
  "runs":8,
  "website":"https://www.hiddenvalleyski.com/"
  },
  {
  "name":"Snow Creek",
  "nearestTown":"Marshall",
  "state":"Missouri",
  "lat":39.468651,
  "long":-94.971964,
  "baseElevation":null,
  "verticalFeet":299,
  "runs":11,
  "website":"https://www.skisnowcreek.com/"
  },

  {
  "name":"Bottineau Winter Park",
  "nearestTown":"Bottineau",
  "state":"North Dakota",
  "lat":48.951,
  "long":-100.473,
  "baseElevation":2270,
  "verticalFeet":180,
  "runs":9,
  "website":"http://skibwp.com/"
  },
  {
  "name":"Frost Fire Ski and Snow Board Area",
  "nearestTown":"Walhalla",
  "state":"North Dakota",
  "lat":48.912,
  "long":-98.068,
  "baseElevation":1070,
  "verticalFeet":330,
  "runs":10,
  "website":"http://www.frostfireskiarea.com/index.html",
  },
  {
  "name":"Huff Hills",
  "nearestTown":"Mandan",
  "state":"North Dakota",
  "lat":46.626944,
  "long":-100.723333,
  "baseElevation":null,
  "verticalFeet":425,
  "runs":21,
  "website":"https://www.huffhills.com/"
  },

  {
  "name":"Alpine Valley Ski Area",
  "nearestTown":"Chesterland",
  "state":"Ohio",
  "lat":41.5303,
  "long":-81.2662,
  "baseElevation":1260,
  "verticalFeet":230,
  "runs":11,
  "website":"https://www.alpinevalleyohio.com/"
  },
  {
  "name":"Boston Mills/Brandywine Ski Resort",
  "nearestTown":"Akron",
  "state":"Ohio",
  "lat":41.283889,
  "long":-81.555556,
  "baseElevation":null,
  "verticalFeet":240,
  "runs":18,
  "website":"https://www.bmbw.com/"
  },
  {
  "name":"Mad River Mountain",
  "nearestTown":"Bellefontaine",
  "state":"Ohio",
  "lat":40.316317,
  "long":-83.680564,
  "baseElevation":1160,
  "verticalFeet":300,
  "runs":23,
  "website":"https://www.skimadriver.com/"
  },

  {
  "name":"Great Bear Recreation Park",
  "nearestTown":"Sioux Falls",
  "state":"South Dakota",
  "lat":43.5821,
  "long":-96.664967,
  "baseElevation":1352,
  "verticalFeet":178,
  "runs":12,
  "website":"https://greatbearpark.com/"
  },
  {
  "name":"Terry Peak",
  "nearestTown":"Lead",
  "state":"South Dakota",
  "lat":44.329,
  "long":-103.835,
  "baseElevation":6011,
  "verticalFeet":1053,
  "runs":30,
  "website":"http://www.terrypeak.com/"
  },

  {
  "name":"Alpine Valley Resort",
  "nearestTown":"Elkhorn",
  "state":"Wisconsin",
  "lat":42.736,
  "long":-88.428,
  "baseElevation":820,
  "verticalFeet":220,
  "runs":20,
  "website":"http://www.alpinevalleyresort.com/"
  },
  {
  "name":"Cascade Mountain",
  "nearestTown":"Portage",
  "state":"Wisconsin",
  "lat":43.503928,
  "long":-89.518017,
  "baseElevation":820,
  "verticalFeet":450,
  "runs":44,
  "website":"http://www.cascademountain.com/"
  },
  {
  "name":"Devil's Head Resort",
  "nearestTown":"Baraboo",
  "state":"Wisconsin",
  "lat":43.423056,
  "long":-89.626944,
  "baseElevation":930,
  "verticalFeet":490,
  "runs":28,
  "website":"https://www.devilsheadresort.com/"
  },
  {
  "name":"Granite Peak Ski Area",
  "nearestTown":"Wausau",
  "state":"Wisconsin",
  "lat":44.928611,
  "long":-89.6825,
  "baseElevation":1250,
  "verticalFeet":700,
  "runs":74,
  "website":"https://www.skigranitepeak.com/index.cfm?",
  },
  {
  "name":"Kettlebowl",
  "nearestTown":"Antigo",
  "state":"Wisconsin",
  "lat":45.271323,
  "long":-88.901979,
  "baseElevation":null,
  "verticalFeet":325,
  "runs":5,
  "website":"https://www.langladecounty.org/tourism/recreation_attractions/?category17=Skiing",
  },
  {
  "name":"Trollhaugen",
  "nearestTown":"Dresser",
  "state":"Wisconsin",
  "lat":45.35125,
  "long":-92.61801,
  "baseElevation":null,
  "verticalFeet":260,
  "runs":24,
  "website":"https://www.trollhaugen.com/index.php",
  },
  {
  "name":"Tyrol Basin",
  "nearestTown":"Mount Horeb",
  "state":"Wisconsin",
  "lat":43.042647,
  "long":-89.77772,
  "baseElevation":870,
  "verticalFeet":260,
  "runs":16,
  "website":"http://www.tyrolbasin.com/"
  },
  {
  "name":"Wilmot Mountain",
  "nearestTown":"Wilmot",
  "state":"Wisconsin",
  "lat":42.5,
  "long":-88.188889,
  "baseElevation":770,
  "verticalFeet":190,
  "runs":23,
  "website":"https://www.wilmotmountain.com/"
  }
];
